export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headLine: 'Unlimited Transactions with Zero Fees',
  description: 'Get Acces to our app that wil give you all of our latest featute updateson time ans subsciption will give you free access for six months',
  buttonLabel: 'Get Started',
  imgStart: false,
  img: require('../../images/svg-1.svg').default,
  alt: 'Car',
  dark: true,
  primary: true,
  darkText: false,
}
export const homeObjTwo = {
  id: 'signup',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'unlimited access',
  headLine: 'Log in to you account any time',
  description: 'Get Acces to our app that wil give you all of our latest featute updateson time ans subsciption will give you free access for six months',
  buttonLabel: 'Get Started',
  imgStart: true,
  img: require('../../images/svg-2.svg').default,
  alt: 'Car',
  dark: false,
  primary: false,
  darkText: true,
}
export const homeObjThree = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'control activity',
  headLine: 'Manage all you activites',
  description: 'Get Acces to our app that wil give you all of our latest featute updateson time ans subsciption will give you free access for six months',
  buttonLabel: 'start now',
  imgStart: false,
  img: require('../../images/svg-3.svg').default,
  alt: 'Car',
  dark: false,
  primary: false,
  darkText: true,
}